all:
	g++ socket_client.cpp main.cpp -lfiles -lpthread -I../files_module/ -L../files_module/ -o client
debug:
	g++ socket_client.cpp main.cpp -lfiles -I../files_module/ -L../files_module/ -o client -g
